name: Digital Garden Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Build Digital Garden
        uses: oleeskild/publish-digitalgarden@v3
        env:
          NOTE_FOLDER: _notes
          BASE_URL: ""
